### ISSUE TITLE
Steamlit Text Box Covered by "Select RAG mode"

### ISSUE THREAD

**Issue by jordanallenlewis** [docker/genai-stack#144]
I just recently started exploring this project and I'm wondering if others have experienced the same issue as me:

On the support bot streamlit front end, the bottom text box where you type in your prompt is mostly covered by the RAG question. Anyone else experiencing this?

![image](https://github.com/docker/genai-stack/assets/42820601/c1f70752-dc28-4682-950e-3f5faa920bff)

**Comment by sopheck** [comment]
:hand: Same here. I haven't used Docker GenAI for a while, but I remember it showing up correctly at first.

**Comment by anirbanbasu** [comment]
<img width="731" alt="Screenshot 2024-04-25 at 8 55 08" src="https://github.com/docker/genai-stack/assets/625357/82b3f3d8-fe2e-4d97-a9ad-eab71a5733f3">

Same for me!

**Comment by llmscope** [comment]
Exactly the same for me — runing in ubuntu 22.04, tried both local firefox browser or NAT another chrome browser.

**Comment by hsiehgeoVA** [comment]
Ran into the same issue. Worked around the problem by giving the fixed position to the chatbox, instead of the "Select RAG  mode" pane. This is done by modifying the CSS style for Streamlit UI in bot.py file: 1) commenting out the "position: fixed" line for the '.element-container:has(aria-lable="Select RAG mode"' element, and 2) adding "position: fixed" line for the '.stChatFloatingInputContainer' element. 

With these changes, the chatbox takes a fixed position at the bottom of the page, while the "Select RAG mode" pane becomes a floating element. So, the chatbox is no longer covered by the "Select RAG mode". This workaround allowed me to continue with the demo app successfully. 

--- Streamlit UI style sheet modification in bot.py file ---
# Streamlit UI
styl = f"""
<style>
    /* not great support for :has yet (hello FireFox), but using it for now */
    .element-container:has([aria-label="Select RAG mode"]) {{
      # position: fixed; # Commented out line
      bottom: 33px;
      background: white;
      z-index: 101;
    }}
    .stChatFloatingInputContainer {{
        bottom: 20px;
        position: fixed; # Added line
    }}
,,,
